### ISSUE TITLE
Array Merge Problem

### ISSUE THREAD

**Issue by Jack12816** [justmoon/node-extend#10]
Extend has a problem with merging arrays.
The elements will be replaced by their indizies
not by uniq values.

Here is a little example:

``` javascript
var extend = require('extend');
var x = extend(
    true,
    {
        x: [700]
    },
    {
        x: [1, 10, 5, 42]
    },
    {
        x: [4, 7]
    }
);

// x = { x: [ 4, 7, 5, 42 ] }
```

**Comment by feeela** [comment]
@ljharb As you said: jQuery.extend also merges arrays – but this module does not. So the behaviour of this module does not match that of jQuery.extend.
