### ISSUE TITLE
no merged when target is not an object or function

### ISSUE THREAD

**Issue by cutsin** [justmoon/node-extend#26]
Sometimes, we cannot know target's type, but target must be merged first:
```javascript
var a = 1, b = 2; extend(true, a, b)
```
`a` expect be `2`, Could you support this please?

**Comment by ljharb** [comment]
I'm not sure what you want it to do. If you pass a non-object target, a new object will be returned. If you pass any source that's not an object, it will be silently ignored.

**Comment by cutsin** [comment]
Thx for ur reply. :laughing: 
ex.:
```javascript
var pool = {
  redis1: { host: '127.0.0.1', posrt: 6379 },
  redis2: { host: '127.0.0.1', posrt: 6000 },
  memcached1: '127.0.0.1:11211',
  memcached2: '127.0.0.1:10000'
}
extend(true, pool.redis1, pool.redis2)
extend(true, pool.memcached1, pool.memcached2)
```
maybe sometimes, we should make the object simplification?

**Comment by ljharb** [comment]
I don't think this would be a simplification. What would `extend(true, pool.memcached1, pool.memcached2)` output?

The use case for this module is that you have two or more objects, and you want to assign/extend all the sources' properties onto the target.

**Comment by cutsin** [comment]
another ex.:
```javascript
var a = {"0":2}, b = [1]
extend(a,b)
console.log(a)  // >> { "0": 1 }
```
maybe `a` should be `[1]` ?

**Comment by ljharb** [comment]
It's impossible to convert an object into an array in-place.

At this point it sounds like you're just imagining features without real use cases - a) this particular module will always conform to jQuery's "extend" algorithm and will not deviate from it, and b) the things you are asking for wouldn't make sense to me in any module.

Thanks for your feedback.
