### ISSUE TITLE
ReferenceError: isPlainObject is not defined

### ISSUE THREAD

**Issue by jonaswindey** [justmoon/node-extend#31]
I have a very strange bug on Chrome which throws this error when my development tools aren't open.

I'm using webpack + react + counterpart (which requires this module). 

The weird thing is that when I open my development tools, the method isPlainObject is clearly defined, but not when it's closed.

On Safari/FF everything works. It seems like a scope issue when requiring this module via webpack that isPlainObject should be called like _this.isPlainObject and exposing this as _this in the top of the index.js.

Any suggestions?

**Comment by ljharb** [comment]
I'm not really sure as I use browserify instead of webpack. Could you provide a gist of the relevant post-webpack code? "this" should be undefined (or the global object) in any IIFE, which all commonJS modules are wrapped in, so I wouldn't expect to, nor accept, using "this" anywhere.

**Comment by danderu** [comment]
@jonaswindey hey, I'm having exactly the same issue here. Did you find any workaround or solution?

**Comment by jonaswindey** [comment]
@danderu no, I finally used react-intl which doesn't rely on counterpart. Let me know if you find a workaround though.

**Comment by damienleroux** [comment]
I has the [same problem](https://github.com/mweststrate/mobservable-react/issues/6) (using React, [mobersvable-react](https://github.com/mweststrate/mobservable-react) & extend). I finally find out that it was my version of extend that was not up to date. I used 2.0 instead of 3.0. Hope it can help others

**Comment by ljharb** [comment]
I'm going to close this unless a reproducible test case can be provided.
