### ISSUE TITLE
Publish most recent changes

### ISSUE THREAD

**Issue by ryanwilliamquinn** [justmoon/node-extend#44]
I saw that you put in a fix for this issue: https://github.com/justmoon/node-extend/issues/43

Could you publish this to npm? We are running into the same problem. Thanks very much.

**Comment by ljharb** [comment]
I can, but if an eslint config inside of `node_modules` is even being picked up, then your gulp setup is what has the bug.

**Comment by ljharb** [comment]
v3.0.2 and v2.0.2 have both been released.
