### ISSUE TITLE
Package contains file not is source control

### ISSUE THREAD

**Issue by skonves** [justmoon/node-extend#49]
`extend@3.0.2` contains an `.editorconfig` file that is not in source control.  Additionally, there are three config files (`.eslintrc`, `.jscs.json`, and `.travis.yml`) that are not necessary to include in the package.  Any of these files are inherently benign; however, the tarball from latest version of the package cannot be consistantly reproduced from source control.

You can reproduce this scan by using "TBV":
`npx tbv verify extend@3.0.2 --verbose`

![screen shot 2019-02-11 at 8 00 48 pm](https://user-images.githubusercontent.com/4925067/52608579-c1bd5300-2e37-11e9-9c46-a4cc423ab505.png)

I recommend adding all root-level dot files to `.npmignore`. Doing so will allow the package to "verify" and will reduce the unpacked module size by 50%.

See also
* https://www.npmjs.com/package/tbv
* https://hackernoon.com/what-if-we-could-verify-npm-packages-c2a319cff758

**Comment by ljharb** [comment]
What do you mean by “verify”? Every package with a build process contains files not in source control.

In this case, it’s a locally present untracked file. I can remove it, but explicitly gitignoring it seems extreme.

**Comment by ljharb** [comment]
Separately, the lint configs are *absolutely* necessary to include, otherwise tests won’t pass in an installed version of this package.

**Comment by skonves** [comment]
> Every package with a build process contains files not in source control

True, but if the package has a `prepare` or `prepack` script, then you can, in theory, run `npm pack` on a clean repo and reproduce file-for-file what is in the published package.

Again, the extra file is benign :+1:.  I was just updating the deps for `express-http-context` and noticed it.

And thanks for maintaining the package 🎉

**Comment by ljharb** [comment]
Thanks for helping out, truly!
