### ISSUE TITLE
Changed default branch name to "main"

### ISSUE THREAD

**Issue by justmoon** [justmoon/node-extend#54]
Changed the default branch name from master to main.

See: https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

@ljharb - Please update your local working copy:

```
$ git checkout master
$ git branch -m master main
$ git fetch
$ git branch --unset-upstream
$ git branch -u origin/main
$ git symbolic-ref refs/remotes/origin/HEAD refs/remotes/origin/main
```

**Comment by ljharb** [comment]
It would probably have been better to wait for github's proper support for this, so that URLs with "master" redirect properly, but noted.
