### ISSUE TITLE
depends on 'extend'. CommonJS or AMD dependencies can cause optimization bailouts. 

### ISSUE THREAD

**Issue by cipchk** [justmoon/node-extend#62]
Can support es module? in angular14 should be warnning: `depends on 'rfdc'. CommonJS or AMD dependencies can cause optimization bailouts.`

How to avoid this warning?

**Comment by ljharb** [comment]
This warning is incorrect, so you should ignore it. There’s no advantage to using ES modules that CJS modules lack.

Unless angular allows you to disable the warning, the only way to avoid it is to not use angular.
